// src/assets/lottie/lv1/preload.ts
export const lv1Images = [
  require('./images/img_0.png'),
  require('./images/img_1.png'),
  require('./images/img_2.png'),
  require('./images/img_3.png'),
  require('./images/img_4.png'),
  require('./images/img_5.png'),
  require('./images/img_6.png'),
  require('./images/img_7.png'),
  require('./images/img_8.png'),
  require('./images/img_9.png'),
  require('./images/img_10.png'),
  require('./images/img_11.png'),
  require('./images/img_12.png'),
  require('./images/img_13.png'),
  require('./images/img_14.png'),
  require('./images/img_15.png'),
  require('./images/img_16.png'),
  require('./images/img_17.png'),
  require('./images/img_18.png'),
  require('./images/img_19.png'),
  require('./images/img_20.png'),
  require('./images/img_21.png'),
];
